spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/treinamentolpi
    username: postgres
    password: root123
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true